"use client";
import React from "react";
import { HeroParallax } from "./ui/hero-parallax";

export default function Portfolio() {
  return <HeroParallax products={products} />;
}

export const products = [
  {
    title: "E-Commerce Platform",
    description: "Full-featured online store with payment integration and inventory management",
    client: "Ethiopian Fashion Boutique",
    category: "Web Development",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=1",
  },
  {
    title: "Social Media Campaign",
    description: "Comprehensive social media strategy resulting in 300% engagement increase",
    client: "Addis Coffee House",
    category: "Digital Marketing",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=2",
  },
  {
    title: "Brand Identity Design",
    description: "Complete brand refresh including logo, color palette, and brand guidelines",
    client: "Tech Startup Ethiopia",
    category: "Branding",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=3",
  },
  {
    title: "Corporate Video Production",
    description: "Professional corporate video showcasing company values and culture",
    client: "Ethiopian Airlines",
    category: "Production",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=4",
  },
  {
    title: "Hotel Booking System",
    description: "Advanced booking platform with real-time availability and payment processing",
    client: "Habesha Hotels Group",
    category: "Web Development",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=5",
  },
  {
    title: "SEO Optimization Campaign",
    description: "Strategic SEO implementation achieving first-page rankings for key terms",
    client: "Local Business Directory",
    category: "Digital Marketing",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=6",
  },
  {
    title: "Real Estate Website",
    description: "Property listing platform with advanced search and virtual tour integration",
    client: "Addis Properties",
    category: "Web Development",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=7",
  },
  {
    title: "Mobile App Development",
    description: "Cross-platform mobile app for food delivery with real-time tracking",
    client: "Quick Delivery ET",
    category: "Web Development",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=8",
  },
  {
    title: "Content Marketing Strategy",
    description: "Data-driven content strategy generating 500+ qualified leads monthly",
    client: "B2B Software Company",
    category: "Digital Marketing",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=9",
  },
  {
    title: "Logo & Brand Guidelines",
    description: "Modern logo design with comprehensive brand identity guidelines",
    client: "Green Energy Initiative",
    category: "Branding",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=10",
  },
  {
    title: "Documentary Production",
    description: "Award-winning documentary highlighting Ethiopian cultural heritage",
    client: "Cultural Heritage Foundation",
    category: "Production",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=11",
  },
  {
    title: "E-Learning Platform",
    description: "Interactive learning management system with video courses and assessments",
    client: "Education First ET",
    category: "Web Development",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=12",
  },
  {
    title: "Social Media Management",
    description: "Complete social media management with content creation and analytics",
    client: "Restaurant Chain",
    category: "Digital Marketing",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=13",
  },
  {
    title: "Package Design",
    description: "Eye-catching product packaging design for premium coffee brand",
    client: "Ethiopian Coffee Exports",
    category: "Branding",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=14",
  },
  {
    title: "Commercial Video Ads",
    description: "High-impact video advertisements for television and digital platforms",
    client: "Telecom Ethiopia",
    category: "Production",
    link: "#contact",
    thumbnail: "https://picsum.photos/600/600?random=15",
  },
];